
# Sistema de Monitoreo MADMex


-Introducción

Las coberturas de 1993, 1995, 1997 y 2000 fueron realizadas con base a imágenes Landsat y Rapid Eye. Se realizaron productos de cambios para los años 2011, 2013 y 2014 y desarrollo en la infraestructura de CONABIO, todo esto en un periodo que abarcó del 2012 al 2015 con el soporte del proyecto ROBIN desarrollado en colaboración con diversas instituciones. Posteriormente del 2016 al 2018 se realizó la integración del sistema con el data cube de Australia, incorporación de segmentadores públicos, debido a que antes se usó uno que requería licencia, se realizó la ampliación de la documentación e instalación e implementación en la nube de amazon. Se realizaron las coberturas de Landsat 2015, Sentinel 2017 y 2018. Así mismo se realizó una serie de tiempo Landsat con un mejor conjunto de entrenamiento más fino que el hecho en el periodo de 2012 al 2015, para el periodo de años entre el 1996 al 2017.)

-Productos Madmex (Breve descripción de cada producto)

Tabla de Productos (síntesis de productos): 
Satélite fuente, Resolución, Año, Escala, Tiempo de procesamiento, Error

-Método (cómo se obtienen los productos)

-Descarga de datos

-Recomendaciones y Conclusiones (que necesidades hay para su producción más ágil y los beneficios obtenidos con estos productos)
